"""
Kindle sender skill — formats transcript/summary/actionables into
clean Kindle-readable HTML and sends via the existing send_to_kindle.py script.

Optional add-on: only used when user explicitly requests Kindle delivery.
"""

import html as html_mod
import os
import re
import subprocess
from pathlib import Path

SEND_SCRIPT = Path("/Users/sarthak/Claude/.claude/agents/tools/send_to_kindle.py")
KINDLE_TMP = Path("/tmp/kindle")


def format_for_kindle(
    title: str,
    transcript: str = "",
    summary: str = "",
    key_points: list[str] | None = None,
    actionables: list[str] | None = None,
    answer: str = "",
    confidence: str = "",
) -> str:
    """Build a clean, Kindle-optimized HTML document from processing results."""

    sections = []

    if answer:
        sections.append(f"<h2>Answer</h2>")
        if confidence:
            badge_color = {"high": "#2d6a4f", "medium": "#7f5539", "low": "#9d0208"}.get(confidence, "#444")
            sections.append(
                f'<p style="display:inline-block;padding:2px 10px;background:{badge_color};'
                f'color:#fff;border-radius:4px;font-size:0.85em;">{html_mod.escape(confidence)} confidence</p>'
            )
        for para in answer.split("\n\n"):
            para = para.strip()
            if para:
                sections.append(f"<p>{html_mod.escape(para)}</p>")

    if actionables:
        sections.append("<h2>Actionables</h2><ul>")
        for item in actionables:
            sections.append(f"<li>{html_mod.escape(item)}</li>")
        sections.append("</ul>")

    if summary:
        sections.append("<h2>Summary</h2>")
        sections.append(_markdown_to_html(summary))

    if key_points:
        sections.append("<h2>Key Points</h2><ul>")
        for pt in key_points:
            sections.append(f"<li>{html_mod.escape(pt)}</li>")
        sections.append("</ul>")

    if transcript:
        sections.append('<h2>Full Transcript</h2>')
        # Truncate very long transcripts for Kindle readability
        display_transcript = transcript[:50000]
        if len(transcript) > 50000:
            display_transcript += "\n\n[Transcript truncated for Kindle delivery]"
        for para in display_transcript.split("\n\n"):
            para = para.strip()
            if para:
                sections.append(f"<p>{html_mod.escape(para)}</p>")

    body = "\n".join(sections)
    safe_title = html_mod.escape(title)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>{safe_title}</title>
<style>
body {{ font-family: Georgia, "Times New Roman", serif; font-size: 1em; line-height: 1.7; margin: 2em; color: #1a1a1a; }}
h1 {{ font-family: Helvetica, Arial, sans-serif; font-size: 1.5em; margin-bottom: 0.5em; border-bottom: 1px solid #ccc; padding-bottom: 0.3em; }}
h2 {{ font-family: Helvetica, Arial, sans-serif; font-size: 1.2em; margin-top: 1.5em; margin-bottom: 0.5em; color: #333; }}
h3 {{ font-family: Helvetica, Arial, sans-serif; font-size: 1.05em; margin-top: 1.2em; margin-bottom: 0.4em; color: #444; }}
p {{ margin-bottom: 0.8em; text-align: justify; }}
ul {{ margin: 0.5em 0 1em 1.5em; }}
li {{ margin-bottom: 0.4em; }}
strong {{ font-weight: bold; }}
blockquote {{ margin: 1em 2em; font-style: italic; color: #444; }}
</style>
</head>
<body>
<h1>{safe_title}</h1>
{body}
<hr>
<p style="font-size:0.8em;color:#888;">Generated by Content Listener Agent</p>
</body>
</html>"""


def send_to_kindle(
    title: str,
    transcript: str = "",
    summary: str = "",
    key_points: list[str] | None = None,
    actionables: list[str] | None = None,
    answer: str = "",
    confidence: str = "",
) -> bool:
    """
    Format results and send to Kindle. Returns True on success.
    """
    if not SEND_SCRIPT.exists():
        print(f"[kindle] send_to_kindle.py not found at {SEND_SCRIPT}")
        return False

    KINDLE_TMP.mkdir(parents=True, exist_ok=True)

    html_content = format_for_kindle(
        title=title,
        transcript=transcript,
        summary=summary,
        key_points=key_points,
        actionables=actionables,
        answer=answer,
        confidence=confidence,
    )

    # Safe filename
    safe_name = "".join(c if c.isalnum() or c in " -_" else "" for c in title)[:80].strip() or "content"
    file_path = KINDLE_TMP / f"{safe_name}.html"
    file_path.write_text(html_content, encoding="utf-8")

    print(f"[kindle] Sending '{title}' to Kindle...")
    result = subprocess.run(
        ["python3", str(SEND_SCRIPT), str(file_path), "--title", title],
        capture_output=True, text=True, timeout=30,
    )

    if result.returncode == 0:
        print(f"[kindle] Sent successfully!")
        return True
    else:
        print(f"[kindle] Failed: {result.stdout} {result.stderr}")
        return False


def _markdown_to_html(md: str) -> str:
    """Convert markdown-structured summary text to HTML for Kindle."""
    lines = md.split('\n')
    out = []
    in_list = False

    for line in lines:
        stripped = line.strip()

        if in_list and not stripped.startswith('- '):
            out.append('</ul>')
            in_list = False

        if not stripped:
            continue
        elif stripped.startswith('## '):
            out.append(f'<h2>{html_mod.escape(stripped[3:])}</h2>')
        elif stripped.startswith('### '):
            out.append(f'<h3>{html_mod.escape(stripped[4:])}</h3>')
        elif stripped.startswith('- '):
            if not in_list:
                out.append('<ul>')
                in_list = True
            text = html_mod.escape(stripped[2:])
            text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
            out.append(f'<li>{text}</li>')
        else:
            text = html_mod.escape(stripped)
            text = re.sub(r'\*\*(.+?)\*\*', r'<strong>\1</strong>', text)
            out.append(f'<p>{text}</p>')

    if in_list:
        out.append('</ul>')

    return '\n'.join(out)


def send_html_to_kindle(title: str, html_content: str) -> bool:
    """Send a pre-built HTML string to Kindle."""
    if not SEND_SCRIPT.exists():
        print(f"[kindle] send_to_kindle.py not found at {SEND_SCRIPT}")
        return False

    KINDLE_TMP.mkdir(parents=True, exist_ok=True)

    safe_name = "".join(c if c.isalnum() or c in " -_" else "" for c in title)[:80].strip() or "content"
    file_path = KINDLE_TMP / f"{safe_name}.html"
    file_path.write_text(html_content, encoding="utf-8")

    print(f"[kindle] Sending '{title}' to Kindle...")
    result = subprocess.run(
        ["python3", str(SEND_SCRIPT), str(file_path), "--title", title],
        capture_output=True, text=True, timeout=30,
    )

    if result.returncode == 0:
        print(f"[kindle] Sent successfully!")
        return True
    else:
        print(f"[kindle] Failed: {result.stdout} {result.stderr}")
        return False
